[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "awfl"
version = "0.1.0"
description = "AWFL: AI Workflows CLI"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "Paul Lorenz" }
]
keywords = ["ai", "workflows", "cli", "serverless", "agents"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Environment :: Console",
  "Operating System :: OS Independent",
]
dependencies = [
  "prompt_toolkit",
  "watchdog",
  "aiohttp",
  "pathspec",
  "requests>=2.31",
  "google-auth",
  "packaging"
]

[project.urls]
Homepage = "https://github.com/awfl-us/cli"
Issues = "https://github.com/awfl-us/cli/issues"

[project.scripts]
awfl = "awfl.awfl_entry:main"
awfl-cli = "awfl.awfl_entry:main"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
